// import { Geist, Geist_Mono, Poppins } from "next/font/google";
'use client'
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "./custom_components/Navbar"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       className = "bg-amber-100"
      >
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
       
      </body>
    </html>
  );
}
